clearing:
    system:
        member:
            id: XA0001
funds:
    transfer:
        success: ACCP
nip:
    url: http://10.7.7.204:9090/api/v1/outward
participant:
    bic: AFXMLRLR
participants:
    path: /var/papss/config/participants.config
server:
    port: 8882
ssl:
    key:
        alias: afxm2

sqlite: 
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:/var/papss/sqlite/db/papss-api-db.db
  username: sa 
  password: sa
spring:
  jpa: 
    database-platform: com.papss.inbound.config.SQLiteDialect 
hibernate: 
  hbm2ddl.auto: update
  show_sql: true