papss:
  system:
    toClearingSystemId: XA0001
    sslKeyAlias: afxm1  

springdoc:
    api-docs:
        enabled: true
        path: /rest-api-docs
    swagger-ui:
        path: /swagger-ui

participants:
    path: /var/papss/config/participants.config

sqlite: 
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:/var/papss/db/sqlite/papss-out-db.db
  username: sa 
  password: sa

spring:
  jpa: 
    database-platform: com.papss.outbound.config.SQLiteDialect 
hibernate: 
  hbm2ddl.auto: update
  show_sql: true

server:
  port: 8881



