papss:
  system:
    toClearingSystemId: XA0001
    pollingSleepTime: 5000
    fundsTransferSuccess: ACCP
    sslKeyAlias: afxm1
    coreUrl: 
        fundsTransfer: http://example.com:9090/api/v1/inbound/fundstransfercredit
        transactionConfirmation: http://example.com:9090/api/v1/inbound/txnconfirmation
        nameInquiry: http://example.com:9090/api/v1/inbound/nameenquiry
        fundsReversalRequest: http://example.com:9090/api/v1/inbound/fundsreversal

participants:
    path: /var/papss/config/participants.config

sqlite: 
  driverClassName: org.sqlite.JDBC
  url: jdbc:sqlite:/var/papss/db/sqlite/papss-in-db.db
  username: sa 
  password: sa

spring:
  jpa: 
    database-platform: com.papss.inbound.config.SQLiteDialect 
hibernate: 
  hbm2ddl.auto: update
  show_sql: true

server:
  port: 8882