clearing:
    system:
        member:
            id: XA0001
funds:
    transfer:
        success: ACCP
nip:
    url: http://10.7.7.204:9090/api/v1/outward
participant:
    bic: AFXMLRLR
participants:
    path: /Users/lingani/IdeaProjects/papss-v2/PAPSS-Inbound-ISO-Service/src/main/resources/participants.config
server:
    port: 8882
spring:
    datasource:
        username: postgres
        password: s3cr3t
        url: jdbc:postgresql://localhost:5432/papss-api-db
        
    flyway:
        baseline-on-migrate: true
        clean-on-validation-error: true
        enabled: true
        ignore-failed-future-migration: true
        out-of-order: true
        password: ${spring.datasource.password}
        url: ${spring.datasource.url}
        user: ${spring.datasource.username}
        validate-on-migrate: false
    jpa:
        show-sql: true
    properties:
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.PostgreSQL81Dialect
            format_sql: true
ssl:
    key:
        alias: afxm2